Feature/allowed dbtypes
Ensembl/ensembl-prodinf-handover pull request #47
Opened 2023-04-12 10:10 UTC by vinay-ebi

New Decorator to check the allowed dbtypes values from remote rest api response

2023-04-12 15:15 UTC, marcoooo requested changes

2023-04-12 15:15 UTC, marcoooo commented on src/ensembl/production/handover/app/main.py
> +                  response = loader.r_open("https://run.mocky.io/v3/9031edf1-4d8c-40f3-8f97-07b85c70bba8")
I believe this shouldn't be this url, right?

2023-04-12 15:15 UTC, marcoooo commented on src/ensembl/production/handover/app/main.py
> +                  uri = os.path.join(cfg.production_portal,f"/api/{cfg.allowed_divisions}/dbtypes")
cfg.allowed_divisions might be a list, say for microbes.

2023-04-12 15:15 UTC, marcoooo commented on src/ensembl/production/handover/app/main.py
> +    def decorator(f):
Why using a decorator there?

2023-04-12 15:16 UTC, marcoooo commented
Could you please add to your pr the following updates made for setup.py https://github.com/Ensembl/ensembl-production-services/blob/80612b5a3f25c22dde376c816bb58c61671e7dbf/setup.py#L27 to use the CI_COMMIT_TAG if present?

2023-04-12 15:18 UTC, vinay-ebi commented on src/ensembl/production/handover/app/main.py
> +                  response = loader.r_open("https://run.mocky.io/v3/9031edf1-4d8c-40f3-8f97-07b85c70bba8")
yes this will be replaced once endpoint set in ensembl-production services portal

2023-04-12 15:25 UTC, vinay-ebi commented on src/ensembl/production/handover/app/main.py
> +    def decorator(f):
To validate the configs before it start execute the endpoint definition : https://github.com/Ensembl/ensembl-prodinf-handover/pull/47/files/34d989deebc016c34a8de806229e8e7b0a863b69#diff-9650b7f6471c6e1c364ce5a77e8d34c4e0f8d595950d3deff93ef95696db8032R167

rather validate inside the endpoint function

2023-05-04 12:00 UTC, marcoooo commented on src/ensembl/production/handover/app/main.py
> +                  uri = os.path.join(cfg.production_portal,f"/api/{cfg.allowed_divisions}/dbtypes")
Mind about allowed_divisions, because it might not be unique in the case of 'microbes'

2023-05-26 09:27 UTC, vinay-ebi commented
This is done via terraform tfvar file

2023-05-26 09:27 UTC, closed without merging